[package]
name = "edsh-common"
version.workspace = true
edition.workspace = true

[dependencies]
iroh.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
